name: Docker Image CI/CD

on:
  push:
    branches:
      - main
      - master  # Trigger action on pushing to master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub (Using Docker Hub credentials)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.tarankaur334 }}
          password: ${{ secrets.Taranjeet@90 }}

      # Build and push MySQL image to Docker Hub
      - name: Build MySQL Image
        run: |
          docker build -t tarankaur334/clo835-mysql:latest ./mysql
          docker push tarankaur334/clo835-mysql:latest

      # Build and push Web Application image to Docker Hub
      - name: Build Web Application Image
        run: |
          docker build -t tarankaur334/clo835-webapp:latest ./app
          docker push tarankaur334/clo835-webapp:latest
