name: Docker Image CI/CD

on:
  push:
    branches:
      - main
      - master  # Trigger action on pushing to master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1  # Use the region you prefer

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build MySQL Image
        run: |
          docker build -t clo835-mysql:latest ./mysql
          docker tag clo835-mysql:latest 471112776853.dkr.ecr.us-east-1.amazonaws.com/clo835-mysql:latest
          docker push 471112776853.dkr.ecr.us-east-1.amazonaws.com/clo835-mysql:latest

      - name: Build Web Application Image
        run: |
          docker build -t clo835-webapp:latest ./app
          docker tag clo835-webapp:latest 471112776853.dkr.ecr.us-east-1.amazonaws.com/clo835-webapp:latest
          docker push 471112776853.dkr.ecr.us-east-1.amazonaws.com/clo835-webapp:latest
