name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin 471112776853.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Docker image
        run: docker build -t clo835-webapp:latest .

      - name: Tag Docker image
        run: docker tag clo835-webapp:latest 471112776853.dkr.ecr.us-east-1.amazonaws.com/clo835-assignment1-app:latest

      - name: Push Docker image
        run: docker push 471112776853.dkr.ecr.us-east-1.amazonaws.com/clo835-assignment1-app:latest

