name: Docker Image CI/CD
on:
  push:
    branches:
      - master  # Trigger action on pushing to master branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build MySQL Image
        run: |
          docker build -t clo835-mysql:latest ./mysql
          docker tag clo835-mysql:latest 471112776853.dkr.ecr.us-east-1.amazonaws.com/clo835-mysql:latest

      - name: Build Web Application Image
        run: |
          docker build -t clo835-webapp:latest .
          docker tag clo835-webapp:latest 471112776853.dkr.ecr.us-east-1.amazonaws.com/clo835-webapp:latest

      - name: Push Images to Amazon ECR
        run: |
          docker push 471112776853.dkr.ecr.us-east-1.amazonaws.com/clo835-mysql:latest
          docker push 471112776853.dkr.ecr.us-east-1.amazonaws.com/clo835-webapp:latest
